<?php

namespace Database\Seeders;

use App\Models\Products;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Products::create([
            'codigo' => 'P001',
            'category_id' => 1,
            'subcategory_id' => 1,
            'visible' => true,
            'price' => 5.99,
            'ganancia' => 1.00,
            'descuento' => 0.50,
            'oferta' => false,
            'name' => 'Sopa de pollo',
            'description' => 'Pollo, fideos, verduras',
            'detalles' => 'Sopa de pollo con fideos y verduras frescas.',
            'marca' => 'Marca 3',
            'tamaño' => 'XL',
            'color' => 'Verde',
            'peso' => 500.00,
            'dimensiones' => json_encode(['alto' => 10, 'ancho' => 10, 'profundidad' => 5]),
            'stock' => 200,
            'contador_ventas' => 0,
            'stock_real' => 200,
            'stock_minimo' => 10,
            'stock_maximo' => 300,
            'imagen_principal' => 'https://example.com/imagen_principal.jpg',
            'imagenes' => json_encode(['https://example.com/imagen1.jpg', 'https://example.com/imagen2.jpg']),
            'video_url' => 'https://example.com/video.mp4',
            'proveedores' => json_encode([['nombre' => 'Proveedor A', 'url' => 'https://proveedorA.com']]),
        ]);
        Products::create(['codigo' => 'P002',
            'category_id' => 1,
            'subcategory_id' => 2,
            'visible' => true,
            'price' => 10.99,
            'ganancia' => 2.00,
            'descuento' => 1.00,
            'oferta' => true,
            'name' => 'Pasta italiana',
            'description' => 'Pasta con salsa de tomate',
            'detalles' => 'Pasta italiana con salsa de tomate y queso parmesano.',
            'marca' => 'Marca 2',
            'tamaño' => 'L',
            'color' => 'Rojo',
            'peso' => 300.00,
            'dimensiones' => json_encode(['alto' => 8, 'ancho' => 8, 'profundidad' => 4]),
            'stock' => 150,
            'contador_ventas' => 0,
            'stock_real' => 150,
            'stock_minimo' => 5,
            'stock_maximo' => 200,
            'imagen_principal' => 'https://example.com/imagen_principal2.jpg',
            'imagenes' => json_encode(['https://example.com/imagen3.jpg', 'https://example.com/imagen4.jpg']),
            'video_url' => 'https://example.com/video2.mp4',
            'proveedores' => json_encode([['nombre' => 'Proveedor B', 'url' => 'https://proveedorB.com']]),
        ]);
        Products::create(['codigo' => 'P003',
            'category_id' => 2,
            'subcategory_id' => 3,
            'visible' => true,
            'price' => 15.99,
            'ganancia' => 3.00,
            'descuento' => 1.50,
            'oferta' => false,
            'name' => 'Ensalada César',
            'description' => 'Lechuga, pollo, crutones, salsa César',
            'detalles' => 'Ensalada César con pollo, crutones y salsa César.',
            'marca' => 'Marca 1',
            'tamaño' => 'M',
            'color' => 'Verde',
            'peso' => 250.00,
            'dimensiones' => json_encode(['alto' => 5, 'ancho' => 10, 'profundidad' => 5]),
            'stock' => 100,
            'contador_ventas' => 0,
            'stock_real' => 100,
            'stock_minimo' => 10,
            'stock_maximo' => 150,
            'imagen_principal' => 'https://example.com/imagen_principal3.jpg',
            'imagenes' => json_encode(['https://example.com/imagen5.jpg', 'https://example.com/imagen6.jpg']),
            'video_url' => 'https://example.com/video3.mp4',
            'proveedores' => json_encode([['nombre' => 'Proveedor C', 'url' => 'https://proveedorC.com']]),
        ]);
        Products::create(['codigo' => 'P004',
            'category_id' => 2,
            'subcategory_id' => 4,
            'visible' => true,
            'price' => 8.99,
            'ganancia' => 1.50,
            'descuento' => 0.75,
            'oferta' => true,
            'name' => 'Hamburguesa clásica',
            'description' => 'Carne, queso, lechuga, tomate',
            'detalles' => 'Hamburguesa clásica con carne, queso, lechuga y tomate.',
            'marca' => 'Marca 4',
            'tamaño' => 'L',
            'color' => 'Marrón',
            'peso' => 200.00,
            'dimensiones' => json_encode(['alto' => 6, 'ancho' => 8, 'profundidad' => 4]),
            'stock' => 120,
            'contador_ventas' => 0,
            'stock_real' => 120,
            'stock_minimo' => 15,
            'stock_maximo' => 180,
            'imagen_principal' => 'https://example.com/imagen_principal4.jpg',
            'imagenes' => json_encode(['https://example.com/imagen7.jpg', 'https://example.com/imagen8.jpg']),
            'video_url' => 'https://example.com/video4.mp4',
            'proveedores' => json_encode([['nombre' => 'Proveedor D', 'url' => 'https://proveedorD.com']]),
        ]);
        Products::create(['codigo' => 'P005',
            'category_id' => 3,
            'subcategory_id' => 5,
            'visible' => true,
            'price' => 20.99,
            'ganancia' => 4.00,
            'descuento' => 2.00,
            'oferta' => false,
            'name' => 'Pizza Margarita',
            'description' => 'Salsa de tomate, queso mozzarella, albahaca',
            'detalles' => 'Pizza Margarita con salsa de tomate, queso mozzarella y albahaca.',
            'marca' => 'Marca 5',
            'tamaño' => 'XL',
            'color' => 'Amarillo',
            'peso' => 400.00,
            'dimensiones' => json_encode(['alto' => 2, 'ancho' => 12, 'profundidad' => 12]),
            'stock' => 80,
            'contador_ventas' => 0,
            'stock_real' => 80,
            'stock_minimo' => 5,
            'stock_maximo' => 100,
            'imagen_principal' => 'https://example.com/imagen_principal5.jpg',
            'imagenes' => json_encode(['https://example.com/imagen9.jpg', 'https://example.com/imagen10.jpg']),
            'video_url' => 'https://example.com/video5.mp4',
            'proveedores' => json_encode([['nombre' => 'Proveedor E', 'url' => 'https://proveedorE.com']]),
        ]);
        Products::create(['codigo' => 'P006',
            'category_id' => 3,
            'subcategory_id' => 6,
            'visible' => true,
            'price' => 12.99,
            'ganancia' => 2.50,
            'descuento' => 1.25,
            'oferta' => true,
            'name' => 'Sushi variado',
            'description' => 'Arroz, pescado, verduras, salsa de soja',
            'detalles' => 'Sushi variado con arroz, pescado, verduras y salsa de soja.',
            'marca' => 'Marca 6',
            'tamaño' => 'M',
            'color' => 'Blanco',
            'peso' => 300.00,
            'dimensiones' => json_encode(['alto' => 3, 'ancho' => 8, 'profundidad' => 6]),
            'stock' => 90,
            'contador_ventas' => 0,
            'stock_real' => 90,
            'stock_minimo' => 10,
            'stock_maximo' => 120,
            'imagen_principal' => 'https://example.com/imagen_principal6.jpg',
            'imagenes' => json_encode(['https://example.com/imagen11.jpg', 'https://example.com/imagen12.jpg']),
            'video_url' => 'https://example.com/video6.mp4',
            'proveedores' => json_encode([['nombre' => 'Proveedor F', 'url' => 'https://proveedorF.com']]),
        ]);
        Products::create(['codigo' => 'P007',
            'category_id' => 4,
            'subcategory_id' => 7,
            'visible' => true,
            'price' => 7.99,
            'ganancia' => 1.00,
            'descuento' => 0.50,
            'oferta' => false,
            'name' => 'Tacos mexicanos',
            'description' => 'Tortilla, carne, lechuga, tomate, queso',
            'detalles' => 'Tacos mexicanos con tortilla, carne, lechuga, tomate y queso.',
            'marca' => 'Marca 7',
            'tamaño' => 'S',
            'color' => 'Amarillo',
            'peso' => 150.00,
            'dimensiones' => json_encode(['alto' => 4, 'ancho' => 6, 'profundidad' => 4]),
            'stock' => 110,
            'contador_ventas' => 0,
            'stock_real' => 110,
            'stock_minimo' => 15,
            'stock_maximo' => 150,
            'imagen_principal' => 'https://example.com/imagen_principal7.jpg',
            'imagenes' => json_encode(['https://example.com/imagen13.jpg', 'https://example.com/imagen14.jpg']),
            'video_url' => 'https://example.com/video7.mp4',
            'proveedores' => json_encode([['nombre' => 'Proveedor G', 'url' => 'https://proveedorG.com']]),
        ]);
        Products::create(['codigo' => 'P008',
            'category_id' => 4,
            'subcategory_id' => 8,
            'visible' => true,
            'price' => 9.99,
            'ganancia' => 1.50,
            'descuento' => 0.75,
            'oferta' => true,
            'name' => 'Enchiladas',
            'description' => 'Tortilla, pollo, salsa verde, queso',
            'detalles' => 'Enchiladas con tortilla, pollo, salsa verde y queso.',
            'marca' => 'Marca 8',
            'tamaño' => 'M',
            'color' => 'Rojo',
            'peso' => 250.00,
            'dimensiones' => json_encode(['alto' => 5, 'ancho' => 7, 'profundidad' => 5]),
            'stock' => 130,
            'contador_ventas' => 0,
            'stock_real' => 130,
            'stock_minimo' => 10,
            'stock_maximo' => 160,
            'imagen_principal' => 'https://example.com/imagen_principal8.jpg',
            'imagenes' => json_encode(['https://example.com/imagen15.jpg', 'https://example.com/imagen16.jpg']),
            'video_url' => 'https://example.com/video8.mp4',
            'proveedores' => json_encode([['nombre' => 'Proveedor H', 'url' => 'https://proveedorH.com']]),
        ]);
        Products::create(['codigo' => 'P009',
            'category_id' => 5,
            'subcategory_id' => 9,
            'visible' => true,
            'price' => 6.99,
            'ganancia' => 1.00,
            'descuento' => 0.50,
            'oferta' => false,
            'name' => 'Empanadas argentinas',
            'description' => 'Masa, carne, cebolla, aceitunas',
            'detalles' => 'Empanadas argentinas con masa, carne, cebolla y aceitunas.',
            'marca' => 'Marca 9',
            'tamaño' => 'S',
            'color' => 'Dorado',
            'peso' => 100.00,
            'dimensiones' => json_encode(['alto' => 3, 'ancho' => 5, 'profundidad' => 3]),
            'stock' => 140,
            'contador_ventas' => 0,
            'stock_real' => 140,
            'stock_minimo' => 20,
            'stock_maximo' => 180,
            'imagen_principal' => 'https://example.com/imagen_principal9.jpg',
            'imagenes' => json_encode(['https://example.com/imagen17.jpg', 'https://example.com/imagen18.jpg']),
            'video_url' => 'https://example.com/video9.mp4',
            'proveedores' => json_encode([['nombre' => 'Proveedor I', 'url' => 'https://proveedorI.com']]),
        ]);
        Products::create(['codigo' => 'P010',
            'category_id' => 5,
            'subcategory_id' => 10,
            'visible' => true,
            'price' => 11.99,
            'ganancia' => 2.00,
            'descuento' => 1.00,
            'oferta' => true,
            'name' => 'Paella valenciana',
            'description' => 'Arroz, mariscos, pollo, verduras',
            'detalles' => 'Paella valenciana con arroz, mariscos, pollo y verduras.',
            'marca' => 'Marca 10',
            'tamaño' => 'L',
            'color' => 'Amarillo',
            'peso' => 500.00,
            'dimensiones' => json_encode(['alto' => 4, 'ancho' => 10, 'profundidad' => 6]),
            'stock' => 160,
            'contador_ventas' => 0,
            'stock_real' => 160,
            'stock_minimo' => 15,
            'stock_maximo' => 200,
            'imagen_principal' => 'https://example.com/imagen_principal10.jpg',
            'imagenes' => json_encode(['https://example.com/imagen19.jpg', 'https://example.com/imagen20.jpg']),
            'video_url' => 'https://example.com/video10.mp4',
            'proveedores' => json_encode([['nombre' => 'Proveedor J', 'url' => 'https://proveedorJ.com']]),
        ]);
        Products::create(['codigo' => 'P011',
            'category_id' => 6,
            'subcategory_id' => 11,
            'visible' => true,
            'price' => 14.99,
            'ganancia' => 2.50,
            'descuento' => 1.25,
            'oferta' => false,
            'name' => 'Ceviche peruano',
            'description' => 'Pescado, limón, cebolla, cilantro',
            'detalles' => 'Ceviche peruano con pescado, limón, cebolla y cilantro.',
            'marca' => 'Marca 11',
            'tamaño' => 'M',
            'color' => 'Blanco',
            'peso' => 200.00,
            'dimensiones' => json_encode(['alto' => 3, 'ancho' => 6, 'profundidad' => 4]),
            'stock' => 170,
            'contador_ventas' => 0,
            'stock_real' => 170,
            'stock_minimo' => 10,
            'stock_maximo' => 210,
            'imagen_principal' => 'https://example.com/imagen_principal11.jpg',
            'imagenes' => json_encode(['https://example.com/imagen21.jpg', 'https://example.com/imagen22.jpg']),
            'video_url' => 'https://example.com/video11.mp4',
            'proveedores' => json_encode([['nombre' => 'Proveedor K', 'url' => 'https://proveedorK.com']]),
        ]);
        Products::create(['codigo' => 'P012',
            'category_id' => 6,
            'subcategory_id' => 12,
            'visible' => true,
            'price' => 17.99,
            'ganancia' => 3.00,
            'descuento' => 1.50,
            'oferta' => true,
            'name' => 'Sushi roll',
            'description' => 'Arroz, pescado, algas, salsa de soja',
            'detalles' => 'Sushi roll con arroz, pescado, algas y salsa de soja.',
            'marca' => 'Marca 12',
            'tamaño' => 'S',
            'color' => 'Blanco',
            'peso' => 150.00,
            'dimensiones' => json_encode(['alto' => 2, 'ancho' => 4, 'profundidad' => 3]),
            'stock' => 180,
            'contador_ventas' => 0,
            'stock_real' => 180,
            'stock_minimo' => 15,
            'stock_maximo' => 220,
            'imagen_principal' => 'https://example.com/imagen_principal12.jpg',
            'imagenes' => json_encode(['https://example.com/imagen23.jpg', 'https://example.com/imagen24.jpg']),
            'video_url' => 'https://example.com/video12.mp4',
            'proveedores' => json_encode([['nombre' => 'Proveedor L', 'url' => 'https://proveedorL.com']]),
        ]);
        Products::create(['codigo' => 'P013',
            'category_id' => 7,
            'subcategory_id' => 13,
            'visible' => true,
            'price' => 19.99,
            'ganancia' => 3.50,
            'descuento' => 1.75,
            'oferta' => false,
            'name' => 'Tacos al pastor',
            'description' => 'Tortilla, carne al pastor, piña, cilantro',
            'detalles' => 'Tacos al pastor con tortilla, carne al pastor, piña y cilantro.',
            'marca' => 'Marca 13',
            'tamaño' => 'M',
            'color' => 'Amarillo',
            'peso' => 250.00,
            'dimensiones' => json_encode(['alto' => 4, 'ancho' => 6, 'profundidad' => 4]),
            'stock' => 190,
            'contador_ventas' => 0,
            'stock_real' => 190,
            'stock_minimo' => 10,
            'stock_maximo' => 230,
            'imagen_principal' => 'https://example.com/imagen_principal13.jpg',
            'imagenes' => json_encode(['https://example.com/imagen25.jpg', 'https://example.com/imagen26.jpg']),
            'video_url' => 'https://example.com/video13.mp4',
            'proveedores' => json_encode([['nombre' => 'Proveedor M', 'url' => 'https://proveedorM.com']]),
        ]);
        Products::create(['codigo' => 'P014',
            'category_id' => 7,
            'subcategory_id' => 14,
            'visible' => true,
            'price' => 22.99,
            'ganancia' => 4.00,
            'descuento' => 2.00,
            'oferta' => true,
            'name' => 'Pizza cuatro quesos',
            'description' => 'Queso mozzarella, queso gorgonzola, queso parmesano, queso gouda',
            'detalles' => 'Pizza cuatro quesos con queso mozzarella, queso gorgonzola, queso parmesano y queso gouda.',
            'marca' => 'Marca 14',
            'tamaño' => 'XL',
            'color' => 'Amarillo',
            'peso' => 600.00,
            'dimensiones' => json_encode(['alto' => 2, 'ancho' => 12, 'profundidad' => 12]),
            'stock' => 200,
            'contador_ventas' => 0,
            'stock_real' => 200,
            'stock_minimo' => 5,
            'stock_maximo' => 250,
            'imagen_principal' => 'https://example.com/imagen_principal14.jpg',
            'imagenes' => json_encode(['https://example.com/imagen27.jpg', 'https://example.com/imagen28.jpg']),
            'video_url' => 'https://example.com/video14.mp4',
            'proveedores' => json_encode([['nombre' => 'Proveedor N', 'url' => 'https://proveedorN.com']]),
        ]);
        Products::create(['codigo' => 'P015',
            'category_id' => 8,
            'subcategory_id' => 15,
            'visible' => true,
            'price' => 25.99,
            'ganancia' => 4.50,
            'descuento' => 2.25,
            'oferta' => false,
            'name' => 'Lasagna de carne',
            'description' => 'Pasta, carne molida, salsa de tomate, queso',
            'detalles' => 'Lasagna de carne con pasta, carne molida, salsa de tomate y queso.',
            'marca' => 'Marca 15',
            'tamaño' => 'L',
            'color' => 'Rojo',
            'peso' => 450.00,
            'dimensiones' => json_encode(['alto' => 5, 'ancho' => 8, 'profundidad' => 5]),
            'stock' => 210,
            'contador_ventas' => 0,
            'stock_real' => 210,
            'stock_minimo' => 10,
            'stock_maximo' => 260,
            'imagen_principal' => 'https://example.com/imagen_principal15.jpg',
            'imagenes' => json_encode(['https://example.com/imagen29.jpg', 'https://example.com/imagen30.jpg']),
            'video_url' => 'https://example.com/video15.mp4',
            'proveedores' => json_encode([['nombre' => 'Proveedor O', 'url' => 'https://proveedorO.com']]),
        ]);
    }
}
